CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    slug TEXT UNIQUE NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_draft BOOLEAN NOT NULL DEFAULT TRUE
);